const test = {
  id: "1751811739220",
  title: "Test title",
  content: {
    children: [
      {
        children: [
          {
            detail: 0,
            format: 2,
            mode: "normal",
            style: "",
            text: "Hehehe",
            type: "text",
            version: 1,
          },
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: " do ",
            type: "text",
            version: 1,
          },
          {
            detail: 0,
            format: 8,
            mode: "normal",
            style: "",
            text: "magic",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "paragraph",
        version: 1,
        textFormat: 2,
        textStyle: "",
      },
      {
        children: [
          {
            detail: 0,
            format: 3,
            mode: "normal",
            style: "",
            text: "This",
            type: "text",
            version: 1,
          },
          {
            detail: 0,
            format: 11,
            mode: "normal",
            style: "",
            text: " is ",
            type: "text",
            version: 1,
          },
          {
            detail: 0,
            format: 15,
            mode: "normal",
            style: "",
            text: "new",
            type: "text",
            version: 1,
          },
          {
            detail: 0,
            format: 11,
            mode: "normal",
            style: "",
            text: " text",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "center",
        indent: 0,
        type: "paragraph",
        version: 1,
        textFormat: 3,
        textStyle: "",
      },
    ],
    direction: "ltr",
    format: "",
    indent: 0,
    type: "root",
    version: 1,
    textFormat: 3,
  },
  isPinned: false,
  createdAt: "2025-07-06T14:22:19.220Z",
  updatedAt: "2025-07-06T14:22:19.220Z",
};
