const test = {
  children: [
    {
      children: [
        {
          detail: 0,
          format: 0,
          mode: "normal",
          style: "",
          text: "2",
          type: "text",
          version: 1,
        },
      ],
      direction: null,
      format: "",
      indent: 0,
      type: "listitem",
      version: 1,
      value: 1,
    },
    {
      children: [
        {
          children: [
            {
              children: [
                {
                  children: [
                    {
                      children: [
                        {
                          children: [
                            {
                              children: [
                                {
                                  detail: 0,
                                  format: 0,
                                  mode: "normal",
                                  style: "",
                                  text: "3.1",
                                  type: "text",
                                  version: 1,
                                },
                              ],
                              direction: null,
                              format: "",
                              indent: 3,
                              type: "listitem",
                              version: 1,
                              value: 1,
                            },
                            {
                              children: [
                                {
                                  detail: 0,
                                  format: 0,
                                  mode: "normal",
                                  style: "",
                                  text: "3.1",
                                  type: "text",
                                  version: 1,
                                },
                              ],
                              direction: null,
                              format: "",
                              indent: 3,
                              type: "listitem",
                              version: 1,
                              value: 2,
                            },
                            {
                              children: [
                                {
                                  detail: 0,
                                  format: 0,
                                  mode: "normal",
                                  style: "",
                                  text: "3.3",
                                  type: "text",
                                  version: 1,
                                },
                              ],
                              direction: null,
                              format: "",
                              indent: 3,
                              type: "listitem",
                              version: 1,
                              value: 3,
                            },
                          ],
                          direction: null,
                          format: "",
                          indent: 0,
                          type: "list",
                          version: 1,
                          listType: "number",
                          start: 1,
                          tag: "ol",
                        },
                      ],
                      direction: null,
                      format: "",
                      indent: 2,
                      type: "listitem",
                      version: 1,
                      value: 1,
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "list",
                  version: 1,
                  listType: "number",
                  start: 1,
                  tag: "ol",
                },
              ],
              direction: null,
              format: "",
              indent: 1,
              type: "listitem",
              version: 1,
              value: 1,
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "list",
          version: 1,
          listType: "number",
          start: 1,
          tag: "ol",
        },
      ],
      direction: null,
      format: "",
      indent: 0,
      type: "listitem",
      version: 1,
      value: 2,
    },
  ],
  direction: null,
  format: "",
  indent: 0,
  type: "list",
  version: 1,
  listType: "number",
  start: 1,
  tag: "ol",
};
